
synonym_dict = {
    "main_headings": ['career objective', 'objective' 'professional qualification',
                      'education', 'educational qualification', 'technical skills',
                      'work experience', 'experience', 'academics', 'projects',
                      'professional summary', 'software languages', 'frameworks',
                      'achievements', 'languages', 'tools', 'skills', 'personal details',
                      'programming languages', 'skill set', 'professional experience',
                      'experience summary', 'work history', 'skills', 'declaration',
                      'achievements', 'major projects', 'education and training',
                      'organization', 'description', 'employement summary', 'training',
                      'trainings', 'internship', 'training and internship',
                      'personal profile', 'profile', 'accomplishments',
                      'academic credentials', 'about', 'certifications',
                      'training and certifications', 'major project undertaken',
                      'extra curricular activities', 'work at', 'awards',
                      'professional background', 'academic background', 'projects undertaken',
                      'hobbies', 'soft skills', 'graduation qualification', 'graduation',
                      'academic details', 'academics', 'academic'],
    "career_objective": ['career objective', 'objective', 'about', 'about me', 'overview',
                         'profile', 'personal profile'],
    "education": ['education', 'educational qualification', 'education and training',
                  'education & training', 'academic credentials', 'academic details',
                  'academics details', 'academic', 'academics', 'academic background'],
    "professional_experience": ['work at', 'professional qualification', 'experience',
                                'work experience', 'professional experience', 'employment summary',
                                'work history', 'professional background'],
    "skills": ['technical skills', 'skills', 'skill set', 'engineering skillset',
               'languages']
}
